apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-disk-claim
spec:
  storageClassName: postgres-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
