apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: "2019-04-01T04:00:16Z"
  generation: 1
  labels:
    app: guestbook
    tier: frontend
  name: frontend
  namespace: default
  resourceVersion: "461277"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/frontend
  uid: a8e201ab-5432-11e9-b5ac-080027c8a3d7
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        tier: frontend
    spec:
      containers:
      - image: gcr.io/google_samples/gb-frontend:v3
        imagePullPolicy: IfNotPresent
        name: php-redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
