apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-dep
spec:
  selector:
    matchLabels:
      name: simple-webapp-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-pod
    spec:
      containers:
      - name: simple-webapp-container
        image: kodekloud/simple-webapp:red
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-dep2
spec:
  selector:
    matchLabels:
      name: simple-webapp-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-pod
    spec:
      containers:
        - name: simple-webapp-container
          image: kodekloud/simple-webapp:blue
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-dep3
spec:
  selector:
    matchLabels:
      name: simple-webapp-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-pod
    spec:
      containers:
        - name: simple-webapp-container
          image: kodekloud/simple-webapp:green
          ports:
            - containerPort: 8080
