apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
#          - name: railsportal-nginx-config
#            mountPath: /etc/nginx/sites-enabled/railsportal.nginx.conf
#            subPath: railsportal.nginx.conf
          - name: wordpress-nginx-config
            mountPath: /etc/nginx/sites-enabled/wordpress.nginx.conf
            subPath: wordpress.nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginxconfig
#        - name: railsportal-nginx-config
#          configMap:
#            name: railsportalnginxconfig
        - name: wordpress-nginx-config
          configMap:
            name: wordpressnginxconfig
