apiVersion: v1
kind: Service
metadata:
  name: nginx

spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: 80
    name: http
  - port: 8081
    nodePort: 30081
    targetPort: 80
    name: http1
  - port: 8082
    nodePort: 30082
    targetPort: 80
    name: http2
  selector:
    app: nginx
